### ISSUE TITLE
Non breaking space (&nbsp;) duplicated when inserting a file

### ISSUE THREAD

**Issue by vmalep** [Sigil-Ebook/Sigil#232]
I noticed that when inserting a image file into an htm file (i.e. <img alt= ...), Sigil duplicates all the non breaking space ("&nbsp;") into all the open files. I have to repeatedly search&replace for "&nbsp;&nbsp;" to "&nbsp;".

Must be a bug, isn't it?

My version is 0.9.5 running on Ubuntu 16.04.

**Comment by dougmassay** [comment]
This bug has been seen before. Unfortunately, the nbsp entity-doubling issue has been tracked down to certain versions (typically Debian testing) of the libxml2 system library, and not Sigil.

I can't duplicate the issue on any of my Linux or Windows testing environments.

Are you using a repo version of Sigil, or did you compile it yourself?

**Comment by vmalep** [comment]
It is the normal package from the Ubuntu repo:
||/ Name                                 Version                 Architecture            Description
ii  sigil                                0.9.5+dfsg-0ubuntu1     amd64                   multi-platform ebook editor

**Comment by mapreri** [comment]
that's the version in xenial.
@dougmassay do you know what are the buggy libxml versions (or do you have any bug reference)?  in ubuntu xenial there is 2.9.3 (+ packaging foo), which is not the last but is not even terribly outdated (2.9.4 has been released in May this year, iiuc).

**Comment by dougmassay** [comment]
Let me track down one of the conversations we had on Mobileread about it a while back. I don't remember what version it was offhand, but I think it was a part of Debian Jesse at the time. Putting a different version of libxml beside the Sigil binary made the doubling issue go away; I do remember that. Let me do some searching and get back to you.

**Comment by dougmassay** [comment]
I was wrong. At the time, it was libxml 2.8.0 on Wheezy that was causing the nbsp doubling issue. Forcing Sigil to use an older 2.7.8 eliminated the issue. I don't remember anyone reporting any trouble with 2.9.1, though, so maybe there was some kind of regression in 2.9.2 or 2.9.3?

I _do_ recall at least one person reporting the same kind of troubles with libxml 2.9.2 on Ubuntu 15.04, but that may have been down to a mismatch between what version of libxml Sigil's QXml (Qt5) was built against not matching the system version of libxml it was trying to make use of. Is xenial's libxml 2.9.3 patched in any way?

I don't see the problem with libxml 2.9.4 on Archlinux, for what it's worth.

The conversation was here: http://www.mobileread.com/forums/showthread.php?t=255887&highlight=libxml

**Comment by kevinhendricks** [comment]
Does it double other entities as well?  The old bug resulted in almost all named and numeric entities outside of the basic xml escapes being doubled.  The fact that the bug is related to lbxml2 is clear but hopping from version to version makes me think it is a bad patch for either libxml2 or Qt which uses libxml2.  I searched the libxml2 release notes for a related change in between the impacted versions in that thread but could never find a likely culprit.  The trouble may be related to changes to prevent entity expansion attacks that have been added in recent years.  Has anyone tried building libxml2 out of the box (without any additional patches) and placing it beside sigil and setting LD_LIBRARY_PATH so it is found first to see if it is libxml2 patch related?

**Comment by dougmassay** [comment]
For what it's worth ... I was able to build Sigil on a fresh Xenial installation with almost entirely repo-supplied libraries (I only used the Sigil-packaged 3rdParty libs -- hunspell, pcre, minizip and zlib) and didn't experience this issue. I'm going to try building using the -DUSE_SYSTEM_LIBS cmake option and see what I get.

**Comment by kevinhendricks** [comment]
After staring at libxml2 commits, there was a time when the sax2 parser effectively doubled every entity because it generated 2 entity callbacks for each entity found and no way to tell if duplicate or not.  Not sure when this was fixed and if fixed in libxml2's internal sax or fixed in libxml2 code itself.  So if there are separate sax packages as libraries, it may be related to the problem.  I am pretty sure Qt and other packages use a sax parser in their QXmlStreamReader code.  So we should look to see if a separate sax parser library is included on effected systems or if there are any distribution specific sax or libxml2 parser patches being used.

**Comment by dougmassay** [comment]
Actually, I retract my earlier statement. I'm seeing weird nbsp doubling on both Archlinux with libxml2 v2.9.4 and on Xenial with libxml2 v2.9.3. Only happens when inserting, typing, splitting, etc... in--wait for it--Book View.

I'll see if I can come up with some detailed steps for you to try and recreate on your Linux system when you get back, Kevin.

Time to revisit getting rid of Book View again. ;)

**Comment by vmalep** [comment]
Hi,

Thanks for following this up so actively.

Hereunder is the libxml2 version I have if it can help. Otherwise, thanks to let me know how any info you may need from me.
```
vmalep@X1Ubuntu:~$ dpkg -l libxml2
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                 Architecture            Description
+++-====================================-=======================-=======================-=============================================================================
ii  libxml2:amd64                        2.9.3+dfsg1-1ubuntu0.1  amd64                   GNOME XML library
ii  libxml2:i386                         2.9.3+dfsg1-1ubuntu0.1  i386                    GNOME XML library
```

**Comment by kevinhendricks** [comment]
Okay, I can recreate this with Linux Mint 18 install freshly updated.  It happens with all entities.  If you add & c o p y ; to Sigil's Preserve Entities Preferences you can watch douldle copywrite symbols being generated when moving from codeview to bookview.

Grabbed the latest hourly snapshot of libxml2-2.9.4 and built it from source and forced it to be used with Sigil and problem still exists.  Next grabbed the official libxml2-2.9.1 and built that from source and forced it to be used with Sigil and now all is fine.  No more problems.

So this appears to be either a regression bug in libxml2 introduced into official libxml2 sources (nothing to do with distribution specific patches) sometime between 2.9.1 and 2.9.4 or an incompatibility introduced between the libxml2 version used with Qt's official 5.4.2 builds.  I will try with released versions of 2.9.2 and 3 to help track down where the breakage is happening in libxml2.

**Comment by kevinhendricks** [comment]
I can confirm, no problems with official libxml2-2.9.2 built from source with Sigil.
I will try official libxml2 2.9.3 built from source next.

**Comment by kevinhendricks** [comment]
libxml2-2.9.3 is broken.  So the breakage is related to entity code and occurred somewhere between official libxml2 2.9.2 and 2.9.3.

Does anyone know a developer on the libxml2 team that might help us track this down and at least alert them to the breakage with Qt and Sigil.

**Comment by kevinhendricks** [comment]
Okay, tracked down the bug to this change introduced in parser.c between 2.9.2 and 2.9.3.  According to git commit messages, this change was meant to fix a bug but seems to have had some side effects:

It is quite a complicated logic test  and obviously it changed something fundamental when it comes to how Qt uses libxml2 when loading a QtWebKit widget with source code when entities are present:

```
diff -ur libxml2-2.9.2/parser.c libxml2-2.9.3/parser.c
--- libxml2-2.9.2/parser.c      2014-10-16 01:57:40.000000000 -0400
+++ libxml2-2.9.3/parser.c      2015-11-20 02:56:41.000000000 -0500

@@ -7235,7 +7278,8 @@
      * far more secure as the parser will only process data coming from
      * the document entity by default.
      */
-    if ((ent->checked == 0) &&
+    if (((ent->checked == 0) ||
+         ((ent->children == NULL) && (ctxt->options & XML_PARSE_NOENT))) &&
         ((ent->etype != XML_EXTERNAL_GENERAL_PARSED_ENTITY) ||
          (ctxt->options & (XML_PARSE_NOENT | XML_PARSE_DTDVALID)))) {
        unsigned long oldnbent = ctxt->nbentities;
```

Reverting this change fixed everything for Sigil/Qt
I don't know their code well enough to figure out what gets broken, but someone at libxml2 project should be able to fix this properly.

For the record, will someone please file and official bug report with libxml2 citing our issue.

**Comment by kevinhendricks** [comment]
BTW,  Someone else has already reported the issue as a regression to libxml2  and provided a patch (untested by me).

See https://bugzilla.gnome.org/show_bug.cgi?id=760367

Perhaps, that patch should be added to libxml2 to see if it fixes the issue they introduced.
```
From 7f1cdb94666d0038a40678a437e92430dd8ecda9 Mon Sep 17 00:00:00 2001
From: David Kilzer <ddkilzer@apple.com>
Date: Sat, 9 Jan 2016 08:55:16 -0800
Subject: [PATCH] Bug 760367: REGRESSION (v2.9.3): Entity is parsed and
 expanded twice under certain conditions
 <https://bugzilla.gnome.org/show_bug.cgi?id=760367>

* parser.c:
(xmlParseReference): Reset was_checked to prevent entity from
being parsed and expanded twice under certain conditions.
---
 parser.c | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/parser.c b/parser.c
index c5741e3..8ede776 100644
--- a/parser.c
+++ b/parser.c
@@ -7392,6 +7392,9 @@ xmlParseReference(xmlParserCtxtPtr ctxt) {
 	}
 	if (ent->checked == 0)
 	    ent->checked = 2;
+
+        /* Prevent entity from being parsed and expanded twice (Bug 760367). */
+        was_checked = 0;
     } else if (ent->checked != 1) {
 	ctxt->nbentities += ent->checked / 2;
     }
-- 
2.4.9 (Apple Git-60)
```

**Comment by kevinhendricks** [comment]
Perhaps, someone could add our issue to that existing libxml2 bug report to show it impacts many Qt projects  so that the fix gets into the next release of libxml2 (or dists can add this patch to their own builds).  It has seen no action since January of this year and no one from libxml2 has bothered to comment on it.

**Comment by dougmassay** [comment]
Thanks, Kevin. Seeing as how there doesn't seem to be an uproar about this with other Linux/Qt/XML-parsing projects, do you think there is possibly a workaround for this (outside of Qt)? Or is the bug that is being exposed just rare enough that most projects don't encounter it? I'm just trying to get a feel for why a bug that involves Linux, Qt, and xml parsing wouldn't be a much bigger deal than it seems to be. I would think there'd be a ton of projects affected. *shrug*

**Comment by kevinhendricks** [comment]
Don't most Windows binary versions of Qt include its own libxml2?  And Mac has its own libxml2 based based version 2.9.1 or earlier.  So the only platform this will hit will be Linux users who have quite new version of libxml2 such as 2.9.3 and 2.9.4.  Right now this hits Xenial based platforms, and Arch.  But it would only show up if the user had entities (such as &nbsp; or &copy;) and then converted to BookView from CodeView and then back (in other words loaded it into a QWebkit based widget and then got the source back out).  The problem is much easier to see with non-whitespace related entities such as &copy;

**Comment by kevinhendricks** [comment]
I updated that issue's V2 patch to work with git-snapshot sources of libxml2 as follows because the indentation in the original patch did not seem to make sense as that "if" was closed by the following line with a semicolon.

Here is the whitespace corrected patch with updated chunk location to work with the latest sources:
```
--- parser.c.orig	2016-07-13 09:25:04.312703211 -0400
+++ parser.c	2016-07-13 09:35:44.419877331 -0400
@@ -7420,6 +7420,10 @@
 	}
 	if (ent->checked == 0)
 	    ent->checked = 2;
+	
+	/* Prevent entity from being parser and expanded twice (Bug 760367). */
+	was_checked = 0;
+
     } else if (ent->checked != 1) {
 	ctxt->nbentities += ent->checked / 2;
     }

```

With this patch and libxml2-git-snapshot.tar.gz from yesterday, everything works as expected.
Hopefully someone will push to get this fix into the next release of libxml2 as we really do not want to have to support our own libxml2 version just to prevent the error.

**Comment by kevinhendricks** [comment]
Actually the original whitespace version may be correct as the indentation of that code block is very confusing unless you can see which "if" the "} else if" was meant to be tied to.  That is why I hate not using braces for even the most simple "if" statements just to make these types of cases clear.

**Comment by dougmassay** [comment]
Yes. It's only affecting Linux Sigil users ... who have the newer distros ... who haven' t been bit hard enough by editing/splitting/merging in Book View to stop doing that yet. ;)

So I agree it's pretty limited in the grand scheme of things. I just hate having issues we can't fix appearing right at the time Sigil starts gaining traction in mainstream repositories.

Oh well. hopefully it sorts itself out sooner rather than later.

Any assurances that this bug is limited to Qt's interaction with libxml2? Just wonderng if it can manifest itself through Python's lxml module. I'm having nightmares of this creeping into the lxml module being distributed with Sigil's Windows package. It currently has libxml2 statically linked into it.

**Comment by kevinhendricks** [comment]
I believe based on comments I found that was posted in 2007 and 2008, and that current libxml2 bug report that Webkit and its derivatives Blink, (and their derivatives QWebEngine and QWebKit) both directly use a sax2 parser from libxml2 to resolve certain entities.   And sax2 used to invoke its entity handler twice each time it found an entity.  A hackish workaround using userdata context values was added to distinguish between entities definitions and entity use or something along those lines.  I did not read things that closely.  So the problem is probably confined to WebKit, Chrome, Qt etc and if nbsp are duplicated, you won't see much difference.  If other visible entities are used, then you can actually see the differences.

BTW: if you add "& c o p y ;" to the Sigil Preserve Entitiy preferences, and add it to an xhtml page in CodeView and then look in Preview, you should see it got doubled.  So the bug impacts Preview as well. It is just that we never copy code out of Preview but we do with BookView that this duplication makes it back into an xhtml file.

**Comment by kevinhendricks** [comment]
Should we add that libxml2 regression fix patch to our docs/ directory here on Sigil and add instructions for Building on Linux docs to build your own libxml2 from git snapshots with this patch and add it to the /usr/local/lib/sigil directory (after creating proper symlinks) or do you think this would just freak out newbies trying to build on Linux?

I would guess a lot of people are going to update to Linux Mint 18 since it gets long term support or Arch for its rolling support and they will be hit hard with constant nbsp duplication if not worse.

If no official fix is forthcoming, we will have to add libxml2 to internal/ in our tree with that patch and adjust the build accordingly.  I really do **not** want to do that but I don't want a bunch of duplicate entity bugs showing in Preview or worse modifying everyone epub that simply looks at their book in BookView just once. 

So this is really bad for us that libxml2 has broken its previous behaviour in 2.9.3 (and released a broken 2.9.4 as well) and has not included the patch from Apple to fix it.

**Comment by kevinhendricks** [comment]
On my stock Linux Mint 18 build I am seeing doubling of smart quotes, bullets, copyright symbols, etc in Preview (making Preview basically worthless) and if you open BookView and change **anything** (even just add a char or delete a single char) this duplication is injected right back into your chapter xhtml code.

Not good at all.

**Comment by kevinhendricks** [comment]
Perhaps we should contact the Linux Distribution people and have them pull Sigil from their repositories until we can include our own libxml2?  Or maybe beg them to include that patch from Apple and push a new libxml2 out there so that current Sigil works and will not damage epubs?

**Comment by kevinhendricks** [comment]
Alternatively, we add code to check the version of libxml2 into Sigil and abort if a broken version is found to prevent people damaging their epubs.

**Comment by mapreri** [comment]
Thanks @kevinhendricks for tracking this down.
FTR I don't directly know anybody related with libxml2, but in the past I dealt with Daniel Veillard (libxml2 maintainer) for a couple of libxslt's bugs, and I found him quite helpful…  I just hope to see him at least comment on the bug, he has an habit of finding all kind of unthinkable issue in proposed patches :)
I can see me uploading a fixed libxml2 to Debian and Ubuntu (both dev version and xenial), but I'd really really prefer to see a comment from Daniel on the proposed patch, even if it looks hell simple.

**Comment by mapreri** [comment]
> Alternatively, we add code to check the version of libxml2 into Sigil and abort if a broken version is found to prevent people damaging their epubs

this won't work with people using packaged sigil, I'd have to upload to xenial a patched sigil to add such an ugly check; not to say it would break if you only check for the version, as if we fix that with a single patch the version of libxml2 wouldn't change.

**Comment by kevinhendricks** [comment]
@manpreri  Do you have a direct contact e-mail for Daniel Veillard so that we can at least alert him to this issue and its counterpart in libxml2 bug reporting system?

**Comment by mapreri** [comment]
@kevinhendricks I'd assume he receives bug notification by emails, at least when I hit the subscribe button on gnome's bugzilla it told me it notified <daniel@veillard.com>.  And you can see how the git commits have <veillard@redhat.com>.  I don't think I even mailed him directly though.

**Comment by dougmassay** [comment]
If we could find a way around the problem of unicode non-breaking-space *characters* being eaten by QPlainTextEdit (et al), then I would be in favor of simply dropping support for entities altogether. Probably a little drastic, but I've always liked characters better anyway. ;)

Let's wait a bit to see what shakes out (either with Veillard taking notice, or @mapreri patching Debian/Unbuntu's libxml2). Remember that something similar happened with libxml2 2.8.x that seemed to get resolved pretty quickly (even if that fix "got broken" again by another commit between 2.9.2 and 2.9.3). Maybe we'll get lucky!

**Comment by kevinhendricks** [comment]
Should we then at least put a warning thread for Linux users of Sigil on Mobileread?  Something along the lines of:

Attention: Linux Users
Due to a bug in libxml2, If you are using Ubuntu 16.04, Arch, Linux Mint 18 or any other distribution that ships with libxml2 >= 2.9.3 through todays git snapshot of libxml2, it is *unsafe* to use Sigil to edit epubs that contain any entities in BookView and that even PreView can not be trusted as it will show duplicate entities when none exist.

And maybe include instructions on how to build a libxml2 from todays git snapshot with this patch and where to install it so that this revised libxml2 is only found for Sigil so nothing else is impacted.

Or something along those lines.

**Comment by kevinhendricks** [comment]
Sent a polite request to both of Daniel's e-mail addresses pointing him at his current libxml2 issue (with v2 patch) and our own issue and asking him to please comment on the safety and merit of that one line v2 patch from Apple.

Not sure if it will get past the spam filters or not.

Doug, do you think we should post a warning (or something similar) on Mobileread just to prevent epubs from being corrupted by unasked for changes on new Linux platforms?

**Comment by dougmassay** [comment]
Yes, we probably should post some sort of warning (and a potential workaround) at Mobileread for Linux users. But I'm betting that patching, building and properly placing a good version of libxml is going to turn off quite a few people who just want to install it from the repo. This sucks.

What if I built a patched version of libxml2 with the oldest gcc compiler I have, and made it available (along with instructions how to do it themselves--for the wary) to those who might be looking for a quick fix? Can you email me the proper patch for the 2.9.4 source?

**Comment by eli-schwartz** [comment]
A month and a half later, and there seems to be complete radio silence from libxml2 on this.
Meanwhile, Sigil now has an option to build a private copy of libxml2.

Does anyone know if Daniel Veillard is even aware of that bug???

**Comment by dougmassay** [comment]
If his bug-tracker service notifies him of new comments to existing reports he should have been reminded of this one, at least.

**Comment by mapreri** [comment]
I sent a ping to the bug, and also opened a [bug report](https://bugs.debian.org/836698) in Debian to see whether the maintainer would be willing to ship that patch (but I don't hold too much hope, I also sent the maintainer a private email asking whether he would like to welcome me into maintaining libxml2 :P)

**Comment by arjunsuresh** [comment]
I'm using Sigil 0.9.7 on Ubuntu 16.04. Everything is fine for me except '&' I use inside MathJax. This is causing Sigil parser to report error. Is this due to this XML parser issue? For example '&' in the following code breaks the parser. 

<script type="math/tex" id="MathJax-Element-34">\begin{bmatrix} 0&2 &8 &5 \\ 2&0 &5 &8 \\ 8&5 &0 &x \\ 5& 8 &x &0 \end{bmatrix}</script>

**Comment by mihailim** [comment]
What code?

**Comment by arjunsuresh** [comment]
Sorry, the script tag was hiding it, now its shown

**Comment by dougmassay** [comment]
> Is this due to this XML parser issue? 

Not likely. The libxml2 issue is all about entity expansion (and doubling). This is something else, I think. I'll let someone with more mathml experience chime in, though.

**Comment by arjunsuresh** [comment]
Thank you. Meanwhile I'll try on other platforms too..

**Comment by kevinhendricks** [comment]
Yes, script tags inside xhtml/xml that have or use xml reserved characters in their content must either xml escape them or wrap the entire section in the proper CDATA tags.

**Comment by arjunsuresh** [comment]
Oh. Okay. Thanks. Actually I'm trying to convert from HTML to epub. So, HTML is having these MathJax part which unfortunately are not put inside CDATA tags. So, to make it work, I should do this rt?

**Comment by kevinhendricks** [comment]
Yes either xml escape the "&" with "&amp;" or try with CDATA tags.  I am not sure that xhtml/epub supports CDATA tags officially on all epub devices.

Another way to handle this is to add a separate script file to the epub and simply reference that new script file instead of inlining the script.

**Comment by arjunsuresh** [comment]
Thank you Kevin. In that case I'll try without rendering mathjax and include a MathJax script with epub. Hope that works.

**Comment by kevinhendricks** [comment]
FWIW, upstream project has now committed Apple's patch to libxml2 master.  Hopefully the Linux distributions can now legally include this patch into their next libxml2 repo builds.

Closing this bug as now fixed in gnome libxml2 master

**Comment by eli-schwartz** [comment]
There was never a *legal* issue. 😄 But hopefully now they will feel confident including it won't break anything.

I requested this patch be included on the Arch Linux bugtracker: [FS#54482](https://bugs.archlinux.org/task/54482)

**Comment by mapreri** [comment]
@eli-schwartz: with ''legal'' @kevinhendricks probably meant that now the various distributors could follow their own policy for patch inclusion, e.g. the Debian maintainers of libxml2 refuse to include any patch not included upstream for fear of hard-to-deal regressions.

**Comment by plastikschnitzer** [comment]
I still see the bug in Kubuntu 18.04 and Sigil 0.9.9

Its very difficult because if you insert new files or separate the file at the cursor position, the number of &nbsp; explodes and if you have more than 100000 &nbsp; in your file, sigil gets very sloooooow and search and replace will take a looong time. Even if you replace all &nbsp; with &#160; this won't help because Sigil will insert &nbsp; automatically. :-( 

Is there any workaround aside hacking the epub container and doing mass editing with the xthml files?

**Comment by dougmassay** [comment]
Yes. Many systems still have a buggy version of libxml2. First make sure updating your system doesn't provide a newer version of libxml2. If it doesn't, the workaround (without building Sigil yourself from scratch) can be found here: https://www.mobileread.com/forums/showthread.php?t=277628
