### ISSUE TITLE
Use book language for guide/nav

### ISSUE THREAD

**Issue by Carmina16** [Sigil-Ebook/Sigil#460]
Please use the book language for the default localized titles that Sigil inserts for `guide` or `nav` elements when the Semantics feature is used. Right now, the UI language is used.

**Comment by kevinhendricks** [comment]
Also please note: guide types and nav types are actually reserved words and part of the spec, so I assume you are talking about the titles.

**Comment by kevinhendricks** [comment]
I have found a way to load a local translator valid for a second language that differs from the ui language.

These changes will go into master  *after* Sigil 1.0.0 is released.

Thank you for your bug report.

**Comment by kevinhendricks** [comment]
The fix for this has now been pushed to master.  Note a translation file (.qm) matching exactly the book language must be installed otherwise the fallback translation for the user interface is used.
Closing this issue as fixed in master.

**Comment by BeckyDTP** [comment]
Thank you for this fix. This is useful.

But I think I found an overlooked little thing (EPUB2).

If we add standard semantics – everything worked.
If we add the semantics "other" – a blank `title=""` appears in the guide.

Sample:
`<reference type="other.introduction" title="" href="intro.xhtml"/>`

Looking at the code, I get the feeling that `title="Introduction"` should appear.

**Comment by kevinhendricks** [comment]
Ah there are translations for those terms although they have [.other] attached to them and therefore are not found.
These all exist and are translated for Landmarks.

So if no title found by translator, it will now check Landmarks as well.

Pushed this to master.

Please let me know if this helped.

**Comment by BeckyDTP** [comment]
Hmmm…
It still doesn't work and the problem is wider.
1. `title` is still empty for `other` semantics.
2. the language is not taken from meta `<dc:language>`, but from `Preferences -> Language -> Default Language for Metadata`
(unless it was meant to be, but the problem report was "Please use the book language ...")

**Comment by kevinhendricks** [comment]
No the default language is so metadata get the proper language code for the book.  It is the primary language of the book.

**Comment by kevinhendricks** [comment]
It is used to set dc:language.

**Comment by kevinhendricks** [comment]
Hmm, being empty makes no sense.  It means the language was found but the string itself was not.  All of these strings exist as translations either for GuideItems or for Landmarks.

So perhaps the translator is not working as expected.  But why only for Guide items with "other"?

I will look into it.

Kevin

**Comment by kevinhendricks** [comment]
Oh, you loaded a book with a dc:language value different from one you would create from empty, that is why those differed.  I will make it parse for the first dc:language value instead.

**Comment by kevinhendricks** [comment]
Okay, this took more work than I thought.  It should now use the language stated in the nav itself for nav titles (since the nav must be standalone machine readable),  and the primary dc:language metadata tag in the guide as the language to translate to.

Also my last "fix" improperly scoped "title" and so it does work once properly handled.

Tested and this now works on my machine.
